name: Release Prometheus Slurm Exporter RPM

on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: Tag to release (e.g. 0.20)
        required: true
jobs:
  build-rocky-rpms:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8.8

    # Required to upload the built RPM to the release
    permissions:
      contents: write

    steps:
      - name: Install prerequisites in container
        run: |
          dnf install -y rpm-build rpmdevtools make git jq curl
          dnf install -y 'dnf-command(config-manager)'
          dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          dnf install -y gh

      - name: Checkout repo
        # Done after install so we have git in the container
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install specific go
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.26.2'

      - name: Generate dnf release number # NB This is the x.y-RELEASE.elX number, NOT the GH release!
        id: release
        run: |
          RELEASE=$(curl -fSsL https://api.github.com/repos/${{ github.repository }}/releases |\
          jq '.[] | select(.name == "${{ github.event.inputs.release-tag }}") | [.assets[].name | select(test(".*\\.rpm$"))] | length' |\
          .github/scripts/generate_release.sh)
          echo "release=${RELEASE}" >> "$GITHUB_OUTPUT"

      - name: Prepare RPMBUILD Environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS,tmp} &&
          echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros &&
          cp README.md ~/rpmbuild/SOURCES &&
          cp LICENSE ~/rpmbuild/SOURCES &&
          cp lib/systemd/prometheus-slurm-exporter.service ~/rpmbuild/SOURCES &&
          cp packages/rpm-ci/*.spec ~/rpmbuild/SPECS

      - name: Prepare tarball from repo
        run: |
          tar czf ~/rpmbuild/SOURCES/${{ github.event.inputs.release-tag }}.tar.gz \
            --transform "s,^\.,prometheus-slurm-exporter-${{ github.event.inputs.release-tag }}," \
            -C $GITHUB_WORKSPACE .

      - name: Debug tarball contents
        run: tar tzf ~/rpmbuild/SOURCES/${{ github.event.inputs.release-tag }}.tar.gz | head -20

      - name: Build RPM
        run: |
          cd ~/rpmbuild || exit 1
          rpmbuild -bb --define '_release ${{ steps.release.outputs.release }}' --define '_version ${{ github.event.inputs.release-tag }}' SPECS/prometheus-slurm-exporter.spec

      - name: Move RPM
        run: |
          mkdir -p RPMS
          cp ~/rpmbuild/RPMS/*/*.rpm RPMS/

      - name: Fix git safe directory for containerisation
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Release RPM
        run: |
          gh release create ${{ github.event.inputs.release-tag }} --generate-notes RPMS/*
        env:
          GH_TOKEN: ${{ github.token }}
